/**
 * @renderx-plugins/components
 * 
 * JSON component definitions for RenderX-based hosts.
 * This package publishes a catalog of components (as JSON) that thin hosts can serve
 * and plugins can consume without coupling.
 */

export interface ComponentMetadata {
  type: string;
  name: string;
  version: string;
  author?: string;
  description?: string;
  category?: string;
  tags?: string[];
  replaces?: string;
}

export interface ComponentTemplate {
  template?: string;
  styles?: {
    css?: string;
    variables?: Record<string, string | number>;
    library?: {
      css?: string;
      variables?: Record<string, string | number>;
    };
  };
}

export interface JsonComponent {
  metadata: ComponentMetadata;
  ui?: ComponentTemplate;
  [key: string]: unknown;
}

export interface ComponentIndex {
  version: string;
  description?: string;
  lastUpdated?: string;
  components: string[];
  metadata?: {
    totalComponents: number;
    categories?: string[];
    autoGenerated?: boolean;
    notes?: string;
  };
}

/**
 * Marker export to indicate this package provides RenderX components
 */
export const RENDERX_COMPONENTS_MARKER = '@renderx-plugins/components';

