/**
 * AUTO-GENERATED FROM: slo-dashboard-business-bdd-specifications.json
 * DO NOT EDIT THIS FILE MANUALLY
 */
import { describe, it, expect } from 'vitest';
import { loadBudgets, loadMetrics, computeCompliance } from '../../src/handlers/metrics';

describe('slo-dashboard business BDD (smoke)', () => {
  it('engine works correctly', async () => {
    const budgets = await loadBudgets();
    const metrics = await loadMetrics();
    const compliance = computeCompliance();
    expect(budgets).toBeDefined();
    expect(metrics).toBeDefined();
    expect(compliance).toBeDefined();
  });
});
